In [ ]:
#

In [1]:
import pandas as pd
import regex as re
import os
from pathlib import Path

In [2]:
df = pd.read_pickle('./poems_abu_alalaa.pkl')

In [6]:
df = df.sort_values(['verses'], ascending=False).reset_index(drop=True)

In [8]:
df.describe()

            verses
count  1612.000000
mean      7.377171
std       8.367442
min       2.000000
25%       3.000000
50%       5.000000
75%       8.000000
max      96.000000

In [10]:
df = df[df['verses'] >= 6].reset_index(drop=True)

In [11]:
df

,title,url,topic,topic_url,meter,meter_url,verses
0,ترنم في نهارك مستعينا,poem22214.html,دينية,Poems-Topics-دينية.html,الوافر,sea-الوافر.html,96
1,أعن وخد القلاص كشفت حالا,poem23633.html,عامه,Poems-Topics-عامه.html,الوافر,sea-الوافر.html,81
2,يرومك والجوزاء دون مرامه,poem23642.html,عامه,Poems-Topics-عامه.html,الطويل,sea-الطويل.html,74
3,يا ساهر البرق أيقظ راقد السمر,poem23634.html,عامه,Poems-Topics-عامه.html,البسيط,sea-البسيط.html,74
4,أودى فليت الحادثات كفاف,poem23630.html,عامه,Poems-Topics-عامه.html,الكامل,sea-الكامل.html,68
...,...,...,...,...,...,...,...
746,باهى رجال وفي جهل يباهونا,poem23477.html,قصيره,Poems-Topics-قصيره.html,البسيط,sea-البسيط.html,6
747,تنافس قوم على رتبة,poem22379.html,عامه,Poems-Topics-عامه.html,المتقارب,sea-المتقارب.html,6
748,تدين مغربي بانتحال,poem23605.html,قصيره,Poems-Topics-قصيره.html,الوافر,sea-الوافر.html,6
749,قد نال خيرا في المعاشر ظاهرا,poem22018.html,قصيره,Poems-Topics-قصيره.html,الكامل,sea-الكامل.html,6
750,ما خص مصرا وبأ وحدها,poem22035.html,قصيره,Poems-Topics-قصيره.html,السريع,sea-السريع.html,6

NameError: name 'abu_alalaa_df' is not defined